name: Deploy Flutter Web

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build web --release --base-href "/Braile-app/"
      - uses: actions/configure-pages@v4
      - uses: actions/upload-artifact@v4
        with:
          path: ./build/web
      - uses: actions/deploy-pages@v4