name: Deploy Flutter Web

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Flutter web
        run: flutter build web --release --base-href "/Braile-app/"
      
      - name: Clean build output
        run: |
          # Remove any potential symlinks or problematic files
          find ./build/web -type l -delete
          # Create clean directory
          mkdir -p ./pages-build
          # Copy files (this breaks any hard links)
          cp -r ./build/web/* ./pages-build/
          # Verify no symlinks remain
          find ./pages-build -type l
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages-build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4